<project xmlns="http://maven.apache.org/POM/4.0.0">

<modelVersion>4.0.0</modelVersion>

<groupId>nz.ac.aut.comp713</groupId>
<artifactId>lifecycle-lab</artifactId>
<version>1.0-SNAPSHOT</version>

<packaging>war</packaging>


<properties>
    <maven.compiler.release>21</maven.compiler.release>
</properties>


<dependencies>

<dependency>
    <groupId>jakarta.platform</groupId>
    <artifactId>jakarta.jakartaee-api</artifactId>
    <version>10.0.0</version>
    <scope>provided</scope>
</dependency>


</dependencies>


<build>

<finalName>lifecycle-lab</finalName>

</build>


</project>